name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print your name
        run: echo "zainab"     

      - name: today Date
        run: Date

      - name: file list
        run: ls  